### ISSUE TITLE
Throws errors if the font isn't found

### ISSUE THREAD

**Issue by tmcw** [mapbox/node-fontnik#112]
`fontnik.load` will throw an error if the given font can't be found or loaded. Instead, it should call the callback with an error argument.

**Comment by mikemorris** [comment]
If a font can't be found or loaded, the error should be handled externally, in an `fs.readFile` callback for example, before passing a buffer on to `fontnik.load`.

The callback *is* currently called with an error argument if `fontnik.load` fails because of an invalid font buffer (a malformed upload or simply `new Buffer(0)` for example).
